id: area_ethereal_nexus
name: The Ethereal Nexus
description: A mystical convergence point where realities blur and time flows strangely.
time_scale: 4
starting_day: 1
starting_hour: 6
starting_minute: 0
biome: ethereal
climate: mild
ambient_lighting: prismatic
weather_profile: stormy
danger_level: 3
magic_intensity: extreme
default_respawn_time: 120
ambient_sound: A gentle humming resonates through the air.
recommended_level: 1
theme: mystical
area_flags:
  safe_zone: false
  pvp_enabled: false
  magic_enhanced: true
time_phases:
  - name: night
    ambient_text: The darkness of night surrounds you.
  - name: morning
    ambient_text: The first light of dawn breaks over the horizon.
  - name: day
    ambient_text: The sun shines overhead.
  - name: evening
    ambient_text: The sun begins to set, casting long shadows.
entry_points:
  - room_1_1_1
triggers:
  - id: nexus_entrance_welcome
    event: on_area_enter
    conditions: []
    actions:
      - type: message_player
        message: >-
          You feel the strange pull of the Ethereal Nexus as you cross its boundary. Time seems to flow differently
          here.
  - id: nexus_exit_farewell
    event: on_area_exit
    conditions: []
    actions:
      - type: message_player
        message: The ethereal energies release their hold on you as you leave the nexus behind.
