# Dark Cave Tunnel - Very low lighting
# Demonstrates need for light sources

id: room_cave_tunnel_1
area_id: area_dark_caves
name: Dark Tunnel
description: A narrow tunnel carved through solid rock. Without a light source, you can barely see your hand in front of your face.
room_type: cave
lighting_override: "5"  # Nearly pitch black (5/100)
exits:
  south: room_cave_entrance
  north: room_cave_chamber
  west: null
  east: null
on_enter_effect: The darkness presses in around you.
on_exit_effect: null

triggers:
  - id: darkness_warning
    event: on_enter
    conditions: []
    actions:
      - type: message_player
        message: "⚫ It's almost completely dark here. You stumble forward cautiously."
